<?php
$translate = $this->plugin('translate');
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headLink()->prependStylesheet('https://use.typekit.net/ftn5sdd.css');
$this->headTitle($this->setting('installation_title', 'Omeka S'))->setSeparator(' · ');
$this->headLink()->appendStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
$this->headLink()->appendStylesheet($this->assetUrl('css/style.css'));
$this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));
$this->headScript()->appendFile($this->assetUrl('js/scripts.min.js'));
$this->trigger('view.layout');
$userBar = $this->userBar();

$siteColors = [
  'navy' => '#002d72',
  //'spirit' => '#67ace5',
  'blue' => '#0072ce',
  'purple' => '#a15a95',
  'orange' => '#cf4520',
  'maroon' => '#76232f',
  'green' => '#286140',
  'yellow' => '#f1c400',
  'gray' => '#414141',
]
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html')->setAttribute('lang', $this->lang()); ?>
    <head>
        <script type="text/javascript">
            document.documentElement.className = 'js';
        </script>
        
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>

        <?php //variables
            $primaryColor = '#002d72';
            if ($this->themeSetting('primary_color') !== null) {
                $primaryColor = $siteColors[$this->themeSetting('primary_color')];
            }

            $secondaryColor = '#67ace5';
            if ($this->themeSetting('secondary_color') !== null) {
                $secondaryColor = $siteColors[$this->themeSetting('secondary_color')];
            }

            $typography = 'modern';
            if ($this->themeSetting('typography') !== null) {
                $typography = $this->themeSetting('typography');
            }

        ?>

        <style>
            :root {
                --color-primary: <?php echo $primaryColor; ?>; 
                --color-secondary: <?php echo $secondaryColor; ?>;

                <?php if ($typography == 'modern'): ?>
                --font-primary: 'proxima-nova', sans-serif;
                --font-display: 'alternate-gothic-extra-cond', sans-serif;
                --font-display-transform: uppercase;
                --line-height-page-title: 1;
                <?php else: ?>
                --font-primary: 'freight-text-pro', serif;
                --font-display: 'freight-text-pro', sans-serif;
                --font-size-page-title: 2rem;
                --font-size-page-title-lg: 2.5rem;
                <?php endif; ?>
                
            }
        </style>
    </head>
    <?php echo $this->htmlElement('body'); ?>
        <a id="skipnav" class="screen-reader" href="#content"><?php echo $this->translate('Skip to main content'); ?></a>
        <?php echo $userBar; ?>
        <header id="header">
            <div class="header-stage">
                <div class="brand-row">
                    <div class="site-width">
                        <div class="brand-stage">
                            <a class="site-brand" href="<?php echo $site->url(); ?>">
                                <span class="logo logo-<?php echo $this->themeSetting('hopkins_logo'); ?>" role="presentation"></span>
                                <span class="brand-text">
                                    <span class="site-title"><?php echo $site->title(); ?></span>

                                    <?php if ($tagline = $this->themeSetting('tagline')): ?>
                                        <span class="site-tagline"><?php echo $tagline; ?></span>
                                    <?php endif; ?>
                                </span>
                            </a>
                            <button aria-controls="main-menu" class="zn-drawer-toggle">Menu</button>
                        </div>
                    </div>
                </div>
                <div class="nav-row">
                    <div class="site-width">
                        <div id="main-menu" class="zn-drawer">
                            <div class="drawer-stage">
                                <div id="search">
                                    <?php echo $this->partial('common/search-form'); ?>
                                </div>
                                <nav>
                                    <?php
                                    echo $site->publicNav()->menu()->renderMenu(null, [
                                        'maxDepth' => $this->themeSetting('nav_depth') - 1
                                    ]);
                                    ?>
                                </nav>
                                <button aria-label="Close menu" class="zn-close-drawer"></button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <main>
            <div id="content" role="main">
                <div class="site-width content-stage">
                    <?php echo $this->messages(); ?>
                    <?php echo $this->content; ?>
                </div>
            </div>
        </main>
        <footer id="footer">
            <div class="site-width">
                <div class="footer-stage">
                    <?php if ($footer_credit = $this->themeSetting('footer_credit')): ?>
                        <div class="footer-credit"><?php echo $footer_credit; ?></div>
                    <?php endif; ?>
                    <a class="site-brand" href="<?php echo $site->url(); ?>">
                        <span class="logo logo-<?php echo $this->themeSetting('hopkins_logo'); ?>" role="presentation"></span>
                        <span class="brand-text">
                            <span class="site-title"><?php echo $site->title(); ?></span>
                        </span>
                    </a>
                </div>

                <div class="terms">
                    <ul>
                        <li><a href="https://www.library.jhu.edu/policies/privacy/" target="_blank">Privacy</a></li>
                        <li><a href="https://www.library.jhu.edu/policies/disclaimer/" target="_blank">Disclaimer</a></li>
                        <li><a href="https://www.library.jhu.edu/policies/" target="_blank">All Policies</a></li>
                    </ul>
                </div>
            </div>
        </footer>
    </body>
</html>
