<div class="zn-featured-display <?php echo $layout; ?>">
    <?php if(isset($attachments[0])): ?>
        <div class="zn-content item resource">
            <?php
            $item = $attachments[0]->item();
            if ($item):
            ?>
                <?php
                $media = $attachments[0]->media() ?: $item->primaryMedia();
                if ($media):
                    echo $item->linkRaw($this->thumbnail($media, $this->thumbnailType));
                endif;
                ?>
                <?php $showTitleOption = $this->showTitleOption; ?>
                <?php if ($showTitleOption == 'item_title'): ?>
                <h3><?php echo $item->link($item->displayTitle()); ?></h3>
                <?php elseif ($showTitleOption == 'file_name'): ?>
                <h3><?php echo $media->displayTitle(); ?></h3>
                <?php endif; ?>
            <?php endif; ?>

            <?php
            $caption = $attachments[0]->caption();
            if ($caption):
            ?>
                <div class="caption"><?php echo $caption; ?></div>
            <?php endif; ?>
        </div>
    <?php endif; ?>
    <div class="zn-content">
        <h2><?php echo $heading; ?></h2>
        <div class="zn-descrition"><?php echo $description; ?></div>
    </div>
</div>


